INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'سهند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'سیس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'دوزدوزان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'تیمورلو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'صوفیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'سردرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'هادیشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'هشترود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'زرنق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'ترکمانچای');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'ورزقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'تسوج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'زنوز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'ایلخچی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'شرفخانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'مهربان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'مبارک شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'تیکمه داش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'باسمنج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'سیه رود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'میانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'خمارلو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'خواجه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'بناب مرند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'قره آغاج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'وایقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'مراغه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'ممقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'خامنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'خسروشاه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'لیلان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'نظرکهریزی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'اهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'بخشایش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'آقکند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'جوان قلعه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'کلیبر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'مرند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'اسکو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'شندآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'شربیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'گوگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'بستان آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'تبریز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'جلفا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'اچاچی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'هریس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'یامچی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'خاروانا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'کوزه کنان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'خداجو(خراجو)');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'آذرشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'شبستر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'سراب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'ملکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'بناب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'هوراند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'کلوانق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'ترک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'عجب شیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (1, N'آبش احمد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'تازه شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'نالوس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'ایواوغلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'شاهین دژ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'گردکشانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'باروق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'سیلوانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'بازرگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'نازک علیا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'ربط');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'تکاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'دیزج دیز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'سیمینه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'نوشین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'میاندوآب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'مرگنلر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'سلماس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'آواجیق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'قطور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'محمودآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'خوی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'نقده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'سرو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'خلیفان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'پلدشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'میرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'اشنویه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'زرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'بوکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'پیرانشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'چهاربرج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'قوشچی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'شوط');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'ماکو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'سیه چشمه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'سردشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'کشاورز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'فیرورق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'محمدیار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'ارومیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'مهاباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (2, N'قره ضیاءالدین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'پارس آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'فخراباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'کلور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'نیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'اردبیل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'اسلام اباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'تازه کندانگوت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'مشگین شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'جعفرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'نمین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'اصلاندوز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'مرادلو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'خلخال');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'کوراییم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'هیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'گیوی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'گرمی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'لاهرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'هشتجین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'عنبران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'تازه کند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'قصابه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'رضی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'سرعین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'بیله سوار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (3, N'آبی بیگلو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'گزبرخوار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'زیار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'زرین شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'گلشن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'پیربکران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'خالدآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'سجزی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'گوگد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'تیران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'ونک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'دهق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'زواره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کاشان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'ابوزیدآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'اصغرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'بافران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'شهرضا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'خور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'مجلسی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'هرند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'فولادشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کمشچه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کلیشادوسودرجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'لای بید');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'قهجاورستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'چرمهین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'رزوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'فریدونشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'طرق رود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'نصرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'برزک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'سفیدشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'سمیرم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'گلدشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'اردستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'جوشقان قالی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'بویین ومیاندشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کرکوند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'درچه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'انارک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'دولت آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'ایمانشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'گرگاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'حسن اباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'سده لنجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'حبیب آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'بهاران شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'میمه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'تودشک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'گلشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'رضوانشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'داران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'علویجه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'نیک آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'مشکات');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'آران وبیدگل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'خوانسار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'نجف آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'منظریه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'فرخی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'دیزیچه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'اژیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'زاینده رود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'خورزوق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'قهدریجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'شاهین شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'بهارستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'چمگردان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'دهاقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'برف انبار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'بادرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کوهپایه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'گلپایگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'عسگران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'حنا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کهریزسنگ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'مهاباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کامو و چوگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'افوس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'زیباشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کوشک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'نایین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'سین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'زازران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'مبارکه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'ورزنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'ورنامخواست');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'شاپورآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'فلاورجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'وزوان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'اصفهان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'باغ بهادران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'چادگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'دامنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'نطنز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'محمدآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'نیاسر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'نوش آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'کمه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'جوزدان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'قمصر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'جندق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'طالخونچه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'خمینی شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'باغشاد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'دستگرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (6, N'ابریشم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'چهارباغ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'آسارا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'کرج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'طالقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'شهرجدیدهشتگرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'محمدشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'مشکین دشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'نظرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'هشتگرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'ماهدشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'اشتهارد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'کوهسار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'گرمدره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'تنکمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'گلسار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'کمال شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (4, N'فردیس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'آبدانان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'شباب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'موسیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'بدره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'ایلام');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'ایوان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'مهران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'آسمان آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'پهله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'مهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'سراب باغ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'بلاوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'میمه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'دره شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'ارکواز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'مورموری');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'توحید');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'دهلران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'لومار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'چوار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'زرنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'صالح آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'سرابله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'ماژین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (5, N'دلگشا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'ریز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'برازجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بندرریگ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'اهرم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'دوراهک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'خورموج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'نخل تقی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'کلمه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بندردیلم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'وحدتیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بنک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'چغادک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بندردیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'کاکی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'جم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'دالکی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بندرگناوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'آبدان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'خارک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'شنبه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بوشکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'انارستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'شبانکاره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'سیراف');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'دلوار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بردستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بادوله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'عسلویه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'تنگ ارم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'امام حسن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'سعد آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بندرکنگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بوشهز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'بردخون');
INSERT INTO Cities (ProvinceId, CityName) VALUES (7, N'آب پخش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'شاهدشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'پیشوا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'جوادآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'ارجمند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'ری');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'نصیرشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'رودهن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'اندیشه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'نسیم شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'صباشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'ملارد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'شمشک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'پاکدشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'باقرشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'احمد آباد مستوفی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'کیلان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'قرچک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'فردوسیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'تهران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'ورامین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'فیروزکوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'فشم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'پرند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'آبعلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'چهاردانگه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'تهران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'بومهن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'وحیدیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'صفادشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'لواسان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'فرون اباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'کهریزک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'رباطکریم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'آبسرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'باغستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'صالحیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'شهریار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'قدس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'تجریش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'شریف آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'حسن آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'اسلامشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'دماوند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (30, N'پردیس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'وردنجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'گوجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'گهرو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'سورشجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'سرخون');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'شهرکرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'منج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'بروجن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'پردنجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'سامان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'فرخ شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'صمصامی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'طاقانک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'کاج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'نقنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'لردگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'باباحیدر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'دستنا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'سودجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'بازفت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'هفشجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'سردشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'فرادبنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'چلیچه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'بن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'فارسان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'شلمزار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'نافچ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'دشتک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'بلداجی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'آلونی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'گندمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'جونقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'ناغان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'هارونی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'چلگرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'کیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'اردل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'سفیددشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (8, N'مال خلیفه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'اسلامیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'شوسف');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'قاین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'عشق آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'طبس مسینا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'ارسک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'آیسک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'نیمبلوک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'دیهوک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'سربیشه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'محمدشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'بیرجند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'فردوس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'نهبندان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'اسفدن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'گزیک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'حاجی آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'سه قلعه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'آرین شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'مود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'خوسف');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'قهستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'بشرویه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'سرایان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'خضری دشت بیاض');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'طبس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'اسدیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (10, N'زهان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'بار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'نیل شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'جنگل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'درود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'رباط سنگ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'سلطان آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'فریمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'گناباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'کاریز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'همت آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'سلامی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'باجگیران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'بجستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'چناران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'درگز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'کلات');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'چکنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'نصرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'بردسکن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'مشهد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'کدکن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'نقاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'قلندرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'کاشمر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'شاندیز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'نشتیفان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'ششتمد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'شادمهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'عشق آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'چاپشلو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'رشتخوار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'قدمگاه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'صالح آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'داورزن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'فرهادگرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'کاخک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'مشهدریزه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'جغتای');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'مزدآوند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'قوچان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'یونسی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'سنگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'نوخندان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'کندر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'نیشابور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'احمدابادصولت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'شهراباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'رضویه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'تربت حیدریه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'باخرز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'سفیدسنگ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'بیدخت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'تایباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'فیروزه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'قاسم آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'سبزوار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'فیض آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'گلمکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'لطف آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'شهرزو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'خرو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'تربت جام');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'انابد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'ملک آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'بایک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'دولت آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'سرخس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'ریوش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'طرقبه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'خواف');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'روداب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (9, N'خلیل آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'چناران شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'راز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'پیش قلعه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'قوشخانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'شوقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'اسفراین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'گرمه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'قاضی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'شیروان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'حصارگرمخان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'آشخانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'تیتکانلو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'جاجرم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'بجنورد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'درق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'آوا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'زیارت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'سنخواست');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'صفی آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'ایور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'فاروج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (11, N'لوجلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'هفتگل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'بیدروبه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'شاوور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'حمزه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'گتوند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'شرافت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'منصوریه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'زهره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'رامهرمز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'بندرامام خمینی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'کوت عبداله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'میداود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'چغامیش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'ملاثانی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'چم گلک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'حر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'شمس آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'آبژدان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'چویبده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'مسجدسلیمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'مقاومت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'ترکالکی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'دارخوین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'سردشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'لالی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'کوت سیدنعیم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'حمیدیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'دهدز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'قلعه تل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'میانرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'رفیع');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'اندیمشک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'الوان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'سالند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'صالح شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'اروندکنار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'سرداران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'تشان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'رامشیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'شادگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'بندرماهشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'جایزان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'بستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'ویس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'اهواز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'فتح المبین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'شهر امام');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'قلعه خواجه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'حسینیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'گلگیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'مینوشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'سماله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'شوشتر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'بهبهان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'هندیجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'ابوحمیظه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'آغاجاری');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'ایذه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'صیدون');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'سیاه منصور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'هویزه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'آزادی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'شوش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'دزفول');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'جنت مکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'آبادان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'گوریه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'خرمشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'مشراگه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'خنافره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'چمران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'امیدیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'سوسنگرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'شیبان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'الهایی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'باغ ملک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (12, N'صفی آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'سجاس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'زرین رود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'آب بر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'ارمغانخانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'کرسف');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'هیدج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'سلطانیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'خرمدره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'نیک پی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'قیدار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'ابهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'دندی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'حلب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'نوربهار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'گرماب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'چورزق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'زنجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'سهرورد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'صایین قلعه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'ماه نشان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (13, N'زرین آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'ایوانکی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'مجن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'دامغان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'سرخه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'مهدی شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'شاهرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'سمنان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'کهن آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'گرمسار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'کلاته خیج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'دیباج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'درجزین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'رودیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'بسطام');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'امیریه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'میامی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'شهمیرزاد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'بیارجمند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'کلاته');
INSERT INTO Cities (ProvinceId, CityName) VALUES (14, N'آرادان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'محمدی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'شهرک علی اکبر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'بنجار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'گلمورتی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'نگور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'راسک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'بنت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'قصرقند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'جالق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'هیدوچ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'نوک آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'زهک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'بمپور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'پیشین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'گشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'محمدآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'زاهدان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'زابلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'چاه بهار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'زرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'بزمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'اسپکه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'فنوج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'سراوان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'ادیمی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'زابل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'دوست محمد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'ایرانشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'سرباز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'سیرکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'میرجاوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'نصرت آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'سوران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'خاش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'کنارک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'محمدان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (15, N'نیک شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'کازرون');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'کارزین (فتح آباد)');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'فدامی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خومه زار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'سلطان شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'فیروزآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'دبیران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'باب انار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'رامجرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'سروستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'قره بلاغ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'ارسنجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'دژکرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'بیرم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'دهرم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'شیراز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'ایزدخواست');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'علامرودشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'اوز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'وراوی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'بیضا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'نی ریز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'کنارتخته');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'امام شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'جهرم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'بابامنیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'گراش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'فسا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'شهرپیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'حسن اباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'کامفیروز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خنج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خانه زنیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'استهبان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'بوانات');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'لطیفی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'فراشبند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'زرقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'صغاد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'اشکنان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'قایمیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'گله دار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'دوبرجی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'آباده طشک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خرامه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'میمند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'افزر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'دوزه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'سیدان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'کوپن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'زاهدشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'قادراباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'سده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'بنارویه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'سعادت شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'شهرصدرا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'سورمق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'حسامی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'جویم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خوزی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'اردکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'قطرویه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'نودان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'مبارک آباددیز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'داراب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'نورآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'کوار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'نوبندگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'حاجی آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خاوران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'مرودشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'کوهنجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'ششده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'مزایجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'ایج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'نوجین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'لپویی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'بهمن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'اهل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'مهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'جنت شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'مشکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'بالاده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'قیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'قطب آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'خانیمن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'مصیری');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'میانشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'صفاشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'اقلید');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'عمادده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'مادرسلیمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'داریان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'رونیز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'کره ای');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'لار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'اسیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'هماشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'آباده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (16, N'لامرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'سگزآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'بیدستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'کوهین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'رازمیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'خرمدشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'آبگرم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'شال');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'شریفیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'اقبالیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'نرجه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'ارداق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'الوند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'خاکعلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'سیردان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'ضیاڈآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'بویین زهرا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'محمدیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'محمودآبادنمونه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'معلم کلایه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'اسفرورین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'آوج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'دانسفهان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'آبیک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'قزوین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (17, N'تاکستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (18, N'کهک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (18, N'قم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (18, N'سلفچگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (18, N'جعفریه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (18, N'قنوات');
INSERT INTO Cities (ProvinceId, CityName) VALUES (18, N'دستجرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'قروه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'توپ آغاج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'سروآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'بویین سفلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'زرینه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'دلبران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'سنندج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'یاسوکند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'موچش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'بانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'مریوان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'سریش آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'صاحب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'دهگلان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'بابارشانی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'دیواندره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'برده رشه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'شویشه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'بیجار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'اورامان تخت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'کانی سور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'کانی دینار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'دزج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'سقز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'بلبان آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'پیرتاج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'کامیاران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'آرمرده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (19, N'چناره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'کهنوج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'بلوک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'پاریز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'گنبکی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'زنگی آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'بم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'خانوک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'کیانشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'جوپار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'عنبرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'جوزم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'نظام شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'لاله زار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'کشکوییه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'زیدآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'هنزا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'چترود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'جبالبارز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'سیرجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'رودبار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'کرمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'بافت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'صفاییه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'منوجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'اندوهجرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'هجدک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'خورسند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'امین شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'بردسیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'رفسنجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'هماشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'محمدآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'اختیارآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'بروات');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'ریحان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'کوهبنان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'ماهان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'دوساری');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'دهج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'فاریاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'گلزار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'بهرمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'بلورد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'فهرج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'کاظم آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'جیرفت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'نجف شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'قلعه گنج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'باغین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'بزنجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'زرند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'نودژ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'گلباف');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'راور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'خاتون اباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'نرماشیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'دشتکار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'مس سرچشمه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'خواجو شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'رابر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'راین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'درب بهشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'یزدان شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'زهکلوت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'محی آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'مردهک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'شهداد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'ارزوییه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'نگار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'شهربابک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (20, N'انار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'سنقر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'شاهو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'بانوره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'تازه آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'هلشی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'جوانرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'قصرشیرین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'نوسود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'کرند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'کوزران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'بیستون');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'حمیل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'گیلانغرب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'سطر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'روانسر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'پاوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'ازگله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'کرمانشاه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'میان راهان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'کنگاور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'سرپل ذهاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'ریجاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'باینگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'هرسین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'اسلام آبادغرب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'سرمست');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'سومار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'نودشه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'گهواره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'رباط');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'صحنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (21, N'گودین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'گراب سفلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'لنده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'سی سخت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'دهدشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'یاسوج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'سرفاریاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'دوگنبدان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'چیتاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'لیکک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'دیشموک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'مادوان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'باشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'پاتاوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'قلعه رییسی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'مارگون');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'چرام');
INSERT INTO Cities (ProvinceId, CityName) VALUES (22, N'سوق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'سیمین شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'مزرعه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'رامیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'فراغی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'گنبدکاووس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'کردکوی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'مراوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'بندرترکمن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'نگین شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'آق قلا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'سرخنکلاته');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'گالیکش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'سنگدوین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'دلند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'بندرگز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'نوده خاندوز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'مینودشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'گرگان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'گمیش تپه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'علی اباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'خان ببین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'کلاله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'اینچه برون');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'فاضل آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'تاتارعلیا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'نوکنده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'آزادشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'انبارآلوم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (23, N'جلین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'منجیل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'شلمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'خشکبیجار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'ماکلوان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'سنگر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'مرجقل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'لیسار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'رضوانشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'رحیم آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'لوندویل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'احمدسرگوراب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'لوشان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'اطاقور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'لشت نشاء');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'فومن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'چوبر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'بازار جمعه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'کلاچای');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'بندرانزلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'املش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'رستم آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'لاهیجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'توتکابن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'لنگرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'کوچصفهان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'صومعه سرا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'اسالم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'دیلمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'رودسر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'کیاشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'شفت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'رودبار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'کومله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'رشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'ماسوله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'خمام');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'ماسال');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'واجارگاه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'هشتپر (تالش)');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'پره سر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'بره سر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'آستارا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'رودبنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'جیرنده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'چاف و چمخاله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'لولمان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'گوراب زرمیخ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'حویق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'سیاهکل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'چابکسر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'آستانه اشرفیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (24, N'رانکوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'چالانچولان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'بیران شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'ویسیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'شول آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'پلدختر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'کوهدشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'هفت چشمه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'بروجرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'الشتر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'مومن آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'دورود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'زاغه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'چقابل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'الیگودرز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'معمولان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'کوهنانی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'نورآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'سپیددشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'سراب دوره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'ازنا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'گراب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'خرم آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'اشترینان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'فیروزآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (25, N'درب گنبد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'گلوگاه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'گلوگاه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'پل سفید');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'دابودشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'چالوس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'کیاسر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'بهنمیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'تنکابن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'کلاردشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'ایزدشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'گتاب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'سلمان شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'ارطه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'امیرکلا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'کوهی خیل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'پایین هولار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'گزنک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'محمودآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'رامسر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'نوشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'خلیل شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'کیاکلا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'نور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'مرزیکلا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'فریدونکنار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'زیرآب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'امامزاده عبدالله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'هچیرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'فریم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'هادی شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'نشتارود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'پول');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'بهشهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'کلارآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'بلده');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'بابل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'جویبار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'آلاشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'آمل');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'نکا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'کتالم وسادات شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'بابلسر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'شیرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'شیرگاه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'رویان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'زرگرمحله');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'عباس اباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'قایم شهر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'خوش رودپی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'مرزن آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'ساری');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'رینه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'سرخرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'خرم آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'کجور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'رستمکلا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'سورک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (26, N'چمستان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'آستانه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'خنجین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'نراق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'کمیجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'آشتیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'رازقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'مهاجران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'غرق آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'خنداب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'قورچی باشی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'خشکرود');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'ساروق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'محلات');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'شازند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'ساوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'میلاجرد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'تفرش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'زاویه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'اراک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'توره');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'نوبران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'فرمهین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'دلیجان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'پرندک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'کارچان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'نیمور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'هندودر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'آوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'جاورسیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'خمین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'مامونیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'داودآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (27, N'شهباز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'بیکاء');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'تیرور');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'گروک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'قشم');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'کوشکنار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'کیش');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'سرگز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'بندرعباس');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'زیارتعلی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'سندرک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'کوهستک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'لمزان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'رویدر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'قلعه قاضی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'فارغان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'ابوموسی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'هشتبندی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'سردشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'درگهان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'پارسیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'کنگ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'جناح');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'تازیان پایین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'دهبارز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'میناب');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'سیریک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'سوزا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'خمیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'چارک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'حاجی اباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'فین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'بندرجاسک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'گوهران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'هرمز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'دشتی');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'بندرلنگه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'بستک');
INSERT INTO Cities (ProvinceId, CityName) VALUES (29, N'تخت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'زنگنه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'دمق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'سرکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'آجین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'جورقان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'برزول');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'فامنین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'سامن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'بهار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'فرسفج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'شیرین سو');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'مریانج');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'فیروزان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'قروه درجزین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'ازندریان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'لالجین');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'گل تپه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'گیان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'ملایر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'صالح آباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'تویسرکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'اسدآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'همدان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'نهاوند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'رزن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'جوکار');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'مهاجران');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'کبودرآهنگ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (28, N'قهاوند');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'مروست');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'مهردشت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'حمیدیا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'تفت');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'اشکذر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'ندوشن');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'یزد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'عقدا');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'بهاباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'ابرکوه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'زارچ');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'نیر');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'اردکان');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'هرات');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'بفروییه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'شاهدیه');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'بافق');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'خضرآباد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'میبد');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'مهریز');
INSERT INTO Cities (ProvinceId, CityName) VALUES (31, N'احمدآباد');
