SET IDENTITY_INSERT dbo.Provinces ON;

INSERT INTO dbo.Provinces(Id, CreatedAt, Name) VALUES 
(1,  GETDATE(), N'آذربایجان شرقی'),
(2,  GETDATE(), N'آذربایجان غربی'),
(3,  GETDATE(), N'اردبیل'),
(4,  GETDATE(), N'البرز'),
(5,  GETDATE(), N'ایلام'),
(6,  GETDATE(), N'اصفهان'),
(7,  GETDATE(), N'بوشهر'),
(8,  GETDATE(), N'چهارمحال و بختیاری'),
(9,  GETDATE(), N'خراسان رضوی'),
(10, GETDATE(), N'خراسان جنوبی'),
(11, GETDATE(), N'خراسان شمالی'),
(12, GETDATE(), N'خوزستان'),
(13, GETDATE(), N'زنجان'),
(14, GETDATE(), N'سمنان'),
(15, GETDATE(), N'سیستان و بلوچستان'),
(16, GETDATE(), N'فارس'),
(17, GETDATE(), N'قزوین'),
(18, GETDATE(), N'قم'),
(19, GETDATE(), N'کردستان'),
(20, GETDATE(), N'کرمان'),
(21, GETDATE(), N'کرمانشاه'),
(22, GETDATE(), N'کهگیلویه و بویراحمد'),
(23, GETDATE(), N'گلستان'),
(24, GETDATE(), N'گیلان'),
(25, GETDATE(), N'لرستان'),
(26, GETDATE(), N'مازندران'),
(27, GETDATE(), N'مرکزی'),
(28, GETDATE(), N'همدان'),
(29, GETDATE(), N'هرمزگان'),
(30, GETDATE(), N'تهران'),
(31, GETDATE(), N'یزد');

SET IDENTITY_INSERT dbo.Provinces OFF;
